name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Xcode versi tertentu
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      # 3. Install dependencies
      - name: Install CocoaPods dependencies
        run: |
          pod install --repo-update
        working-directory: GameFeed

      # 4. Test
      - name: Test
        run: |
          xcodebuild \
            -workspace GameFeed.xcworkspace \
            -scheme GameFeed \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            IPHONEOS_DEPLOYMENT_TARGET=15.0 \
            clean test

      # 5. SwiftLint
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
