name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Xcode versi tertentu
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      # 3. Build & Test dengan SPM
      - name: Build & Test
        run: |
          xcodebuild \
            -project GameFeed.xcodeproj \
            -scheme GameFeed \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            clean test

      # 4. SwiftLint
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
