name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Xcode
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      # 3. Fix Package.resolved file is corrupted or malformed problem
      - name: Patch Xcode 15.3
        uses: 2sem/patch-package-resolved@v2

      # 4. Build & Test with SPM
      - name: Build & Test
        run: |
          xcodebuild \
            -project GameFeed.xcodeproj \
            -scheme GameFeed \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            clean test

      # 4. SwiftLint
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
